// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0R1YIblXHawmvYcaNQeBx7wVtF4PMiGA',
    appId: '1:357260268285:web:c9dae4b8dc1a65d0f96494',
    messagingSenderId: '357260268285',
    projectId: 'demologin-b57f4',
    authDomain: 'demologin-b57f4.firebaseapp.com',
    storageBucket: 'demologin-b57f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-I9XbWn_MybvLUHd6qJigCttdGtsVKo',
    appId: '1:357260268285:android:a60da5fd205353ccf96494',
    messagingSenderId: '357260268285',
    projectId: 'demologin-b57f4',
    storageBucket: 'demologin-b57f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfowP0sQv8sX3DNAsaM-i8yaXw6ttH0uw',
    appId: '1:357260268285:ios:5990ba97779796fdf96494',
    messagingSenderId: '357260268285',
    projectId: 'demologin-b57f4',
    storageBucket: 'demologin-b57f4.appspot.com',
    iosBundleId: 'com.example.practiceLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfowP0sQv8sX3DNAsaM-i8yaXw6ttH0uw',
    appId: '1:357260268285:ios:1178d17470cca8e5f96494',
    messagingSenderId: '357260268285',
    projectId: 'demologin-b57f4',
    storageBucket: 'demologin-b57f4.appspot.com',
    iosBundleId: 'com.example.practiceLogin.RunnerTests',
  );
}
